function G = robot_gravity(in1,g,L_45,L_6,m1,m2,m3,m4,m5,m6,m7)
%ROBOT_GRAVITY
%    G = ROBOT_GRAVITY(IN1,g,L_45,L_6,M1,M2,M3,M4,M5,M6,M7)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    13-May-2025 23:24:09

theta_4 = in1(4,:);
theta_5 = in1(5,:);
theta_6 = in1(6,:);
t2 = cos(theta_4);
t3 = theta_4+theta_5;
t5 = theta_6.*2.0;
t6 = cos(t3);
t7 = t3+theta_6;
t9 = t3+theta_5;
t11 = t3+t5;
t8 = cos(t7);
t10 = cos(t9);
t12 = cos(t11);
G = [0.0;(g.*(m2+m3.*2.0+m4.*2.0+m5.*2.0+m6.*2.0+m7.*2.0))./2.0;0.0;(g.*(L_45.*m4.*cos(theta_4.*2.0).*-2.0+L_6.*m6.*t8.*2.0+L_6.*m7.*t8.*2.0-L_6.*m6.*t12+L_45.*m4.*t2.*2.0+L_45.*m5.*t2.*2.0+L_45.*m6.*t2.*2.0+L_45.*m7.*t2.*2.0+L_45.*m5.*t6.*2.0+L_45.*m6.*t6.*2.0+L_45.*m7.*t6.*2.0-L_45.*m5.*t10))./2.0;L_6.*g.*m6.*t8+L_6.*g.*m7.*t8-(L_6.*g.*m6.*t12)./2.0+L_45.*g.*m5.*t6+L_45.*g.*m6.*t6+L_45.*g.*m7.*t6-L_45.*g.*m5.*t10;L_6.*g.*(m6.*t8+m7.*t8-m6.*t12);0.0];
end
